apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8srequireresources
  annotations:
    description: Requires containers to have resource limits and requests set.
spec:
  crd:
    spec:
      names:
        kind: K8sRequireResources
      validation:
        openAPIV3Schema:
          type: object
          properties:
            limits:
              type: array
              items:
                type: string
            requests:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequireresources

        violation[{"msg": msg}] {
          container := input_containers[_]
          not container.resources.limits
          msg := sprintf("Container <%v> has no resource limits", [container.name])
        }

        violation[{"msg": msg}] {
          container := input_containers[_]
          not container.resources.requests
          msg := sprintf("Container <%v> has no resource requests", [container.name])
        }

        violation[{"msg": msg}] {
          container := input_containers[_]
          resource_type := input.parameters.limits[_]
          not container.resources.limits[resource_type]
          msg := sprintf("Container <%v> has no <%v> limit", [container.name, resource_type])
        }

        violation[{"msg": msg}] {
          container := input_containers[_]
          resource_type := input.parameters.requests[_]
          not container.resources.requests[resource_type]
          msg := sprintf("Container <%v> has no <%v> request", [container.name, resource_type])
        }

        input_containers[c] {
          c := input.review.object.spec.containers[_]
        }

        input_containers[c] {
          c := input.review.object.spec.initContainers[_]
        }
